name: CI Report
on:
  workflow_run:
    workflows: [ CI ]
    types: [ completed ]

permissions:
  checks: write

jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      # needed unless run with comment_mode: off
      pull-requests: write
      # required by download step to access artifacts API
      actions: read    
    steps:
      - name: Download Test Report
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow.id }}
          run_id: ${{ github.event.workflow_run.id }}
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '**/*.xml'
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        with:
          commit: ${{github.event.workflow_run.head_sha}}
          report_paths: '**/*.xml'
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          event_file: Event File/event.json
          event_name: ${{ github.event.workflow_run.event }}
          files: "**/*.xml"
